services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres  
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=monografias

volumes:
  postgres_data: