# Generated by Django 5.0.3 on 2024-04-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo da Monografia')),
                ('resumo', models.TextField(verbose_name='Resumo')),
                ('palavrasChaves', models.TextField(verbose_name='Palavras-chaves')),
                ('dataEntrega', models.DateTimeField(verbose_name='Data de Entrega')),
                ('arquivo', models.FileField(blank=True, upload_to='pdfs/', verbose_name='Documento em PDF')),
            ],
        ),
    ]
