# Generated by Django 5.0.3 on 2024-04-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='autor',
            field=models.ManyToManyField(to='equipe.pesquisador', verbose_name='Autor'),
        ),
    ]
