# Generated by Django 5.0.3 on 2024-04-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_documentos_coorientador'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='areaConcentracao',
            field=models.CharField(blank=True, choices=[('Ciências Sociais e Humanas', 'Csh'), ('Ciências Exatas e Tecnológicas', 'Cet'), ('Ciências da Saúde', 'Cse'), ('Ciências Biológicas e Ambientais', 'Cba'), ('Artes e Comunicação', 'Aco'), ('Economia e Administração', 'Eao'), ('Educação', 'Edu'), ('Direito e Ciências Jurídicas', 'Dcj'), ('Tecnologia da Informação e Ciência da Computação', 'Tic'), ('Gestão e Políticas Públicas', 'Gpp')], max_length=50, null=True, verbose_name='Área de Concentração'),
        ),
        migrations.AddField(
            model_name='documentos',
            name='notaFinal',
            field=models.FloatField(blank=True, null=True, verbose_name='Nota final'),
        ),
    ]
