# Generated by Django 5.0.3 on 2024-04-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_documentos_areaconcentracao_documentos_notafinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='areaConcentracao',
            field=models.CharField(blank=True, choices=[('Ciências Sociais e Humanas', 'Humanas'), ('Ciências Exatas e Tecnológicas', 'Tecnolgia'), ('Ciências da Saúde', 'Saude'), ('Ciências Biológicas e Ambientais', 'Biologicas'), ('Artes e Comunicação', 'Artes'), ('Economia e Administração', 'Economia'), ('Educação', 'Educacao'), ('Direito e Ciências Jurídicas', 'Direito'), ('Tecnologia da Informação e Ciência da Computação', 'Computacao')], max_length=50, null=True, verbose_name='Área de Concentração'),
        ),
    ]
