# Generated by Django 5.0.3 on 2024-04-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0008_alter_documentos_areaconcentracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='areaConcentracao',
            field=models.CharField(blank=True, choices=[('HUMANAS', 'Ciências Sociais e Humanas'), ('TECNOLGIA', 'Ciências Exatas e Tecnológicas'), ('SAUDE', 'Ciências da Saúde'), ('BIOLOGICAS', 'Ciências Biológicas e Ambientais'), ('ARTES', 'Artes e Comunicação'), ('ECONOMIA', 'Economia e Administração'), ('EDUCACAO', 'Educação'), ('DIREITO', 'Direito e Ciências Jurídicas'), ('COMPUTACAO', 'Tecnologia da Informação e Ciência da Computação')], max_length=50, null=True, verbose_name='Área de Concentração'),
        ),
    ]
