# Generated by Django 5.0.3 on 2024-04-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0009_alter_documentos_areaconcentracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='areaConcentracao',
            field=models.CharField(blank=True, choices=[('CSH', 'Ciências Sociais e Humanas'), ('CET', 'Ciências Exatas e Tecnológicas'), ('CSE', 'Ciências da Saúde'), ('CBA', 'Ciências Biológicas e Ambientais'), ('ACO', 'Artes e Comunicação'), ('EAO', 'Economia e Administração'), ('EDU', 'Educação'), ('DCJ', 'Direito e Ciências Jurídicas'), ('TIC', 'Tecnologia da Informação e Ciência da Computação')], max_length=50, null=True, verbose_name='Área de Concentração'),
        ),
    ]
